name: Maven Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting the current repo
        uses: actions/checkout@v2  # checking out the code in the current repository

      - name: Set up JDK 11.0.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install Google Chrome # Running shell script from scripts folder
        run: |
          chmod +x ./scripts/InstallChrome.sh
            ./scripts/InstallChrome.sh

      - name: Invoke a lifecycle phase
        run: mvn install

      - name: Compile
        run: mvn clean test
