name: Maven Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting the current repo
        uses: actions/checkout@v2  # checking out the code in the current repository

      - name: Set up JDK 11.0.11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.11

      - name: Build Maven project
        run: mvn -b package --file pom.xml

      - name: List all the files
        run: ls -a

      - name: What is in target folder?
        run: |
          cd target
          ls -a
